In [ ]:
# Activity 5.01 Clustering Sales Data Using K-Means
# Load the dataset as a DataFrame and inspect the data:

In [2]:
import pandas as pd
file_url = 'https://raw.githubusercontent.com/''PacktWorkshops/'\
'The-Applied-Artificial-Intelligence-Workshop/'\
'master/Datasets/'\
'Sales_Transactions_Dataset_Weekly.csv'
df = pd.read_csv(file_url)
df

,Product_Code,W0,W1,W2,W3,W4,W5,W6,W7,W8,...,Normalized 42,Normalized 43,Normalized 44,Normalized 45,Normalized 46,Normalized 47,Normalized 48,Normalized 49,Normalized 50,Normalized 51
0,P1,11,12,10,8,13,12,14,21,6,...,0.06,0.22,0.28,0.39,0.50,0.00,0.22,0.17,0.11,0.39
1,P2,7,6,3,2,7,1,6,3,3,...,0.20,0.40,0.50,0.10,0.10,0.40,0.50,0.10,0.60,0.00
2,P3,7,11,8,9,10,8,7,13,12,...,0.27,1.00,0.18,0.18,0.36,0.45,1.00,0.45,0.45,0.36
3,P4,12,8,13,5,9,6,9,13,13,...,0.41,0.47,0.06,0.12,0.24,0.35,0.71,0.35,0.29,0.35
4,P5,8,5,13,11,6,7,9,14,9,...,0.27,0.53,0.27,0.60,0.20,0.20,0.13,0.53,0.33,0.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
806,P815,0,0,1,0,0,2,1,0,0,...,0.00,0.33,0.33,0.00,0.00,0.33,0.00,0.00,0.67,0.00
807,P816,0,1,0,0,1,2,2,6,0,...,0.43,0.43,0.57,0.29,0.57,0.71,0.71,0.71,0.86,0.71
808,P817,1,0,0,0,1,1,2,1,1,...,0.50,0.00,0.00,0.50,0.50,0.00,0.00,0.00,1.00,0.75
809,P818,0,0,0,1,0,0,0,0,1,...,0.00,0.00,0.00,0.50,0.50,0.00,0.00,0.00,1.00,0.00
810,P819,0,1,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.33

In [ ]:
# Creating a new DataFrame without the unnecessary columns, as shown in
# the following code snippet (the first 55 columns of the dataset). You should use
# the inplace parameter to help you:

In [4]:
df2 = df.drop(df.iloc[:, 0:55], inplace = False, axis = 1)

In [5]:
# Creating a k-means clustering model with 8 clusters and with random state = 8:
# We build a k-means model with the default value for every parameter except
# for n_clusters=8 with random_state=8 in order to obtain 8 clusters and
# reproducible results.
# Retrieving the labels from the clustering algorithm:

In [6]:
from sklearn.cluster import KMeans
k_means_model = KMeans(n_clusters=8, random_state=8)
k_means_model.fit(df2)

labels = k_means_model.labels_
labels

array([6, 6, 2, 6, 6, 1, 6, 6, 2, 2, 6, 2, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 6, 2, 5, 5, 6, 5, 5, 5, 2, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 5,
       6, 5, 6, 5, 5, 6, 5, 5, 2, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 6, 2, 5,
       5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 2, 5, 6, 6, 2, 6, 6, 6, 5, 5, 5, 5,
       5, 5, 2, 5, 5, 1, 2, 6, 5, 2, 6, 4, 5, 5, 5, 6, 6, 1, 2, 4, 6, 6,
       4, 6, 5, 5, 5, 2, 6, 6, 5, 5, 6, 6, 2, 6, 6, 6, 6, 5, 5, 5, 5, 6,
       5, 6, 5, 5, 5, 6, 5, 5, 5, 5, 5, 2, 6, 6, 5, 6, 5, 2, 6, 2, 6, 2,
       6, 6, 6, 6, 6, 2, 6, 6, 6, 2, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 5, 5,
       6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 2, 1,
       2, 1, 6, 2, 2, 2, 4, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 7, 3, 7, 3,
       7, 3, 3, 7, 7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 7, 3, 3, 7, 7,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 3, 7, 3, 3, 3, 2, 1, 4, 2,
       1, 2, 2, 1, 1, 1, 4, 3, 3, 3, 3, 3, 7, 3, 3, 3, 4, 7, 3, 5, 1, 1,
       7, 4, 0, 3, 6, 4, 6, 6, 1, 2, 6, 2, 2, 2, 6, 2, 5, 6, 6, 6, 4, 6,
       5, 5, 6, 6, 6, 2, 4, 6, 5, 6, 2, 6, 6, 2, 2, 4, 6, 6, 6, 2, 6, 1,
       6, 5, 5, 6, 6, 6, 6, 4, 4, 7, 2, 1, 4, 4, 4, 7, 7, 7, 7, 3, 3, 3,
       3, 3, 1, 1, 7, 1, 4, 2, 4, 4, 1, 4, 4, 1, 1, 1, 4, 4, 4, 7, 7, 7,
       4, 7, 7, 3, 3, 3, 3, 3, 7, 3, 4, 4, 1, 6, 4, 1, 7, 4, 4, 1, 1, 1,
       1, 1, 1, 6, 2, 2, 1, 1, 2, 1, 1, 1, 4, 6, 1, 4, 2, 7, 4, 3, 3, 3,
       3, 7, 4, 7, 3, 3, 3, 3, 1, 1, 1, 1, 7, 4, 2, 4, 2, 3, 7, 4, 7, 7,
       0, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 0, 7, 7, 3, 3, 3, 7, 3, 7, 3, 3,
       7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 7, 4, 7, 7, 7, 4, 7, 7, 6, 2, 2,
       2, 6, 5, 1, 6, 2, 1, 4, 1, 1, 1, 6, 2, 6, 2, 2, 1, 2, 2, 2, 1, 2,
       4, 1, 6, 1, 5, 1, 2, 2, 2, 2, 5, 2, 6, 2, 2, 6, 5, 4, 6, 2, 5, 2,
       2, 2, 2, 1, 1, 2, 2, 4, 2, 5, 2, 1, 5, 5, 2, 2, 2, 6, 5, 6, 5, 5,
       6, 6, 5, 1, 6, 2, 2, 2, 6, 6, 6, 4, 2, 2, 6, 4, 6, 4, 1, 4, 4, 0,
       7, 3, 7, 3, 7, 2, 6, 6, 2, 2, 1, 4, 1, 1, 7, 1, 1, 7, 2, 1, 4, 1,
       7, 1, 7, 7, 4, 7, 7, 3, 7, 7, 7, 3, 1, 4, 4, 1, 1, 1, 1, 1, 6, 5,
       6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 6, 4, 6, 2, 1, 5, 6, 5, 1, 1, 3, 1,
       6, 1, 3, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 7, 3,
       3, 3, 7, 3, 3, 7, 7, 3, 4, 4, 1, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
       7, 7, 3, 3, 3, 1, 1, 7, 3, 3, 7, 4, 7, 7, 4, 4, 4, 7, 1, 7, 7, 3,
       3, 3, 3, 3, 0, 3, 0, 3, 3, 3, 3, 3, 3, 7, 7, 7, 3, 3, 3, 7, 7, 7,
       3, 7, 4, 7, 7, 7, 7, 7, 7, 0, 4, 7, 4, 7, 7, 3, 3, 1, 4, 4, 7, 7,
       7, 3, 3, 3, 3, 4, 0, 4, 7, 3, 7, 4, 7, 7, 3, 3, 3, 3, 3, 7, 3, 3,
       3, 3, 1, 2, 1, 1, 1, 6, 7, 4, 4, 4, 1, 4, 4, 7, 7, 4, 4, 4, 1, 7,
       4, 7, 1, 1, 6, 4, 7, 7, 7, 3, 6, 4, 4, 4, 3, 4, 7, 7, 3],
      dtype=int32)

In [7]:
# Now, from the first DataFrame, df, keep only the W columns and add the labels
# as a new column, as shown in the following code snippet:
# In the preceding code snippet, we removed all the unneeded columns and added
# labels as a new column in the DataFrame.

In [8]:
df.drop(df.iloc[:, 53:], inplace = True, axis = 1)
df.drop('Product_Code', inplace = True, axis = 1)
df['label'] = labels
df

,W0,W1,W2,W3,W4,W5,W6,W7,W8,W9,...,W43,W44,W45,W46,W47,W48,W49,W50,W51,label
0,11,12,10,8,13,12,14,21,6,14,...,7,8,10,12,3,7,6,5,10,6
1,7,6,3,2,7,1,6,3,3,3,...,4,5,1,1,4,5,1,6,0,6
2,7,11,8,9,10,8,7,13,12,6,...,14,5,5,7,8,14,8,8,7,2
3,12,8,13,5,9,6,9,13,13,11,...,10,3,4,6,8,14,8,7,8,6
4,8,5,13,11,6,7,9,14,9,9,...,11,7,12,6,6,5,11,8,9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
806,0,0,1,0,0,2,1,0,0,1,...,1,1,0,0,1,0,0,2,0,3
807,0,1,0,0,1,2,2,6,0,1,...,3,4,2,4,5,5,5,6,5,4
808,1,0,0,0,1,1,2,1,1,0,...,0,0,2,2,0,0,0,4,3,7
809,0,0,0,1,0,0,0,0,1,0,...,0,0,1,1,0,0,0,2,0,7
810,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,3

In [9]:
# Perform the aggregation (use the groupby function from pandas) in order
# to obtain the yearly average sale of each cluster, as shown in the following
# code snippet:

# In the preceding code snippet, we first used the groupby function with the
# sum() method of the DataFrame to calculate the sum of every product's sales
# for each W column and cluster, and stored the results in df_agg. We then
# used the groupby function with the count() method on a single column (an
# arbitrary choice) of df to obtain the total number of products per cluster (note
# that we also had to rename the W0 column after the aggregation). The next step
# was to sum all the sales columns of df_agg in order to obtain the total sales
# for each cluster. Finally, we calculated the yearly_average_sales for each
# cluster by dividing total_sales by count_product. We also included a final
# step to sort out the cluster by the highest yearly_average_sales.

In [11]:
df_agg = df.groupby('label').sum()
df_final = df[['label','W0']].groupby('label').count()
df_final=df_final.rename(columns = {'W0':'count_product'})
df_final['total_sales'] = df_agg.sum(axis = 1)
df_final['yearly_average_sales']= \
df_final['total_sales'] / df_final['count_product']
df_final.sort_values(by='yearly_average_sales', \
ascending=False, inplace = True)
df_final

       count_product  total_sales  yearly_average_sales
label
5                128       173808           1357.875000
6                129        86341            669.310078
2                 96        48778            508.104167
1                 90        43112            479.022222
4                 85        17390            204.588235
7                107         4348             40.635514
0                  8           96             12.000000
3                168         1414              8.416667